allowBuilds:
  '@parcel/watcher': true
  cypress: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true

minimumReleaseAgeExclude:
  - '@angular-devkit/architect@0.2102.13'
  - '@angular-devkit/core@21.2.13'
  - '@angular-devkit/schematics@21.2.13'
  - '@angular/cli@21.2.13'
  - '@schematics/angular@21.2.13'
  - '@angular/build@21.2.13'
  - '@angular/ssr@21.2.13'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - cypress
  - esbuild
  - lmdb
  - msgpackr-extract

overrides:
  qs@>=6.11.1 <=6.15.1: '>=6.15.2'
  uuid@<14.0.0: '>=14.0.0'
