allowBuilds:
  '@parcel/watcher': true
  cypress: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - cypress
  - esbuild
  - lmdb
  - msgpackr-extract

overrides:
  qs@>=6.11.1 <=6.15.1: '>=6.15.2'
  uuid@<14.0.0: '>=14.0.0'
